trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  bkstrgrg: 'tfstateRG01'
  bkstrg: 'tfstate01684258857'
  bkcontainer: 'tfstate'
  bkstrgkey: 'terraform.tfstate'
  tfworkingdir: '$(System.DefaultWorkingDirectory)/scripts/vmlab_terraform'

stages:
  - stage: tfdestroy
    jobs:
      - job: destroy
        steps:
          - task: TerraformInstaller@0
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV3@3
            displayName: init
            inputs:
              provider: 'azurerm'
              workingDirectory: '$(tfworkingdir)'
              command: 'init'
              backendServiceArm: 'JcoleDevops'
              backendAzureRmResourceGroupName: '$(bkstrgrg)'
              backendAzureRmStorageAccountName: '$(bkstrg)'
              backendAzureRmContainerName: '$(bkcontainer)'
              backendAzureRmKey: '$(bkstrgkey)'
          - task: TerraformTaskV3@3
            displayName: plan
            inputs:
              provider: 'azurerm'
              workingDirectory: '$(tfworkingdir)'
              command: 'plan'
              environmentServiceNameAzureRM: 'JcoleDevops'
          - task: TerraformTaskV3@3
            displayName: destroy
            inputs:
              provider: 'azurerm'
              workingDirectory: '$(tfworkingdir)'
              command: 'destroy'
              environmentServiceNameAzureRM: 'JcoleDevops'